# Generated by Django 4.2.7 on 2023-12-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connecte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.IntegerField(default=0),
        ),
    ]
