# Generated by Django 4.2.7 on 2023-12-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connecte', '0002_alter_produit_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
